project:
  type: book

book:
  title: "Python Plotting Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/py-plot-notes
  site-url: https://py-plot-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Matplotlib"
      chapters:
        - text: Outline
          href: contents/matplotlib/outline-matplotlib.qmd
        - text: "Module 1: Foundations and Mental Model"
          href: contents/matplotlib/m1-foundation.ipynb
        - text: "Module 2: The Object-Oriented API"
          href: contents/matplotlib/m2-object-oriented-api.ipynb

format:
  html:
    theme:
      light:
      - cosmo
      dark:
      - darkly
    toc-depth: 4

freeze: auto
